### ISSUE TITLE
Change the link sharing graphic

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/site#4] opened 2019-01-07 14:20 UTC
Right now it shows TEH: http://files.fp20.org/0abb0d5d0446

Don't know why though because in the old system is something different

**Comment by az** [comment] 2019-01-07 14:21
@marek-berlin duplicate of https://github.com/ecommerceberlin/site/issues/2. closing :>

**Closed** 2019-01-07 14:21 UTC
